import Head from "next/head";
import HeroComponent from "../components/HeroComponent";
import LogoComponent from "../components/LogoComponent";
import ScreenSizeComponent from "../components/ScreenSizeComponent";
import SocialFollowComponent from "../components/SocialFollowComponent";

export default function Home() {
  return (
    <div className="bg-[#0e1829]">
      <Head>
        <title>Muzzamil Banday</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      {/* <ScreenSizeComponent /> */}

      <div
        className={
          "flex flex-col px-20 sm:px-24 md:px-28 lg:px-32 xl:px-48 relative"
        }
      >
        <div className="absolute top-20 left-1/2 transform -translate-x-1/2 sm:top-5 sm:translate-x-0 sm:left-5">
          <LogoComponent />
        </div>
        <div className=" flex flex-col min-h-screen relative ">
          <HeroComponent />
        </div>

        <SocialFollowComponent />
      </div>
    </div>
  );
}
